---
common: &default_settings
  app_name: <%= ENV["NEW_RELIC_APPNAME"] || 'braumeister.org' %>
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  monitor_mode: false
  ssl: true
  developer_mode: false
  capture_params: true
  log_level: warn
  background:
    monitor_mode: true

development:
  <<: *default_settings
  developer_mode: true

production:
  <<: *default_settings
  monitor_mode: true
